from fpdf import FPDF
import datetime

class PDFReport(FPDF):
    def header(self):
        # Logo / Title
        self.set_font('Arial', 'B', 24)
        self.set_text_color(0, 51, 102) # Dark blue
        self.cell(0, 15, 'PROSPER VISTA', 0, 1, 'L')
        self.set_font('Arial', 'I', 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'Institutional Intelligence Briefing', 0, 1, 'L')
        self.line(10, 35, 200, 35)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Generated on {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")} | Page {self.page_no()}', 0, 0, 'C')

def generate_intelligence_report(ticker, current_price, target_price, confidence, sentiment, whale_activity, prob_up, p50, max_up, max_down):
    pdf = PDFReport()
    pdf.add_page()
    
    # Title Section
    pdf.set_font('Arial', 'B', 18)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, f'ASSET: {ticker}', 0, 1)
    
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, f'Current Price: INR {current_price:,.2f}', 0, 1)
    pdf.cell(0, 8, f'Projected Neural Target: INR {target_price:,.2f}', 0, 1)
    
    chg = ((target_price - current_price) / current_price) * 100
    pdf.cell(0, 8, f'Expected Change: {chg:+.2f}%', 0, 1)
    pdf.cell(0, 8, f'Model Confidence (R2): {confidence*100:.1f}%', 0, 1)
    pdf.ln(5)
    
    # Sentiment & Whale
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 10, 'Market Mechanics & Sentiment', 0, 1)
    
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, f'Global Sentiment Mood: {sentiment}', 0, 1)
    pdf.cell(0, 8, f'Detected Whale Activity: {whale_activity}', 0, 1)
    pdf.ln(5)
    
    # Monte Carlo Risk
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 10, '30-Day Predictive Risk Assessment', 0, 1)
    
    pdf.set_font('Arial', '', 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, f'Probability of Profit: {prob_up:.1f}%', 0, 1)
    pdf.cell(0, 8, f'Neural Landing Zone (Median): INR {p50:,.2f}', 0, 1)
    pdf.cell(0, 8, f'Max Structural Upside (P90): {max_up:+.1f}%', 0, 1)
    pdf.cell(0, 8, f'Max Structural Drawdown (P10): {max_down:+.1f}%', 0, 1)
    
    pdf.ln(10)
    pdf.set_font('Arial', 'I', 10)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 6, "Disclaimer: This report is generated by Prosper Vista's predictive algorithms. It is for informational purposes only and does not constitute financial advice. Institutional models are subject to market volatility.")
    
    filename = f"report_{ticker}_{datetime.datetime.now().strftime('%Y%m%d%H%M')}.pdf"
    pdf.output(filename)
    return filename
